### ISSUE TITLE
schematic for ESP12

### ISSUE THREAD

**Issue by budi99ok** [papconst/PZEM-004T-Arduino-ESP8266-soft-serial#1]
Hi,
could you attach schematic ?
related to example code..
---
PZEM_004T pzem(10,11);// Arduino: 10,11
	              // ESP-01: 0,2
                      // ESP-12F: 0-5 or 12-15
---

Thanks

**Comment by papconst** [comment]
`PZEM_004T pzem(10,11);// Arduino: 10,11`
Attach new pzem to 10th and 11th pins of Arduino.

```
// ESP-01: 0,2
// ESP-12F: 0-5 or 12-15
```
On ESP-01 you can use pins 0 and 2;
On ESP-12F you may use pins from 0,1,2,3,4,5 and 12,13,14,15

**Comment by budi99ok** [comment]
Thank you..
